name: soil_id

services:
  db:
    image: ghcr.io/techmatters/soil-id-db:0.3
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soil_id # default database
